stages:
  download_data:
    cmd: uv run predicting_outcomes_in_heart_failure/data/dataset.py
    deps:
    - predicting_outcomes_in_heart_failure/data/dataset.py
    outs:
    - data/raw/heart.csv
  preprocessing:
    cmd: uv run predicting_outcomes_in_heart_failure/data/preprocess.py
    deps:
    - predicting_outcomes_in_heart_failure/data/preprocess.py
    - data/raw/heart.csv
    outs:
    - data/interim/preprocessed.csv
  split_data:
    cmd: uv run predicting_outcomes_in_heart_failure/data/split_data.py
    deps:
    - predicting_outcomes_in_heart_failure/data/split_data.py
    - data/interim/preprocessed.csv
    outs:
    - data/processed
  training:
    cmd: uv run predicting_outcomes_in_heart_failure/modeling/train.py
    deps:
    - predicting_outcomes_in_heart_failure/modeling/train.py
    - data/processed/train.csv
    outs:
    - models/decision_tree.joblib
    - models/random_forest.joblib
    - models/logreg.joblib
    - reports/decision_tree
    - reports/random_forest
    - reports/logreg
  evaluation:
    cmd: uv run predicting_outcomes_in_heart_failure/modeling/evaluate.py
    deps: 
    - predicting_outcomes_in_heart_failure/modeling/evaluate.py
    - models
