{
 "title": "CardioTrack Monitoring",
 "time": { "from": "2025-12-28T18:29:02.645Z", "to": "2025-12-28T18:34:39.538Z" },
 "panels": [
  {
   "title": "Services UP",
   "type": "stat",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "up{job=~\"fastapi|prometheus\"}\r\n",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Success rate",
   "type": "stat",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 *\r\n(\r\n  sum(rate(cardiotrack_api_http_requests_total{status=\"2xx\"}[5m]))\r\n  /\r\n  sum(rate(cardiotrack_api_http_requests_total[5m]))\r\n)\r\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Request for second",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "req/s" } },
   "targets": [
    {
     "expr": "sum(rate(cardiotrack_api_http_requests_total[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Request by endpoint",
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "topk(\r\n  5,\r\n  sum by (handler) (\r\n    rate(cardiotrack_api_http_requests_total{\r\n      handler=~\"^/$|^/predictions$|^/batch-predictions$|^/explanations$|^/cards/.*|^/model/.*\"\r\n    }[5m])\r\n  )\r\n)\r\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "HTTP latency",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(\r\n  0.95,\r\n  sum by (le) (\r\n    rate(cardiotrack_api_http_request_duration_seconds_bucket[5m])\r\n  )\r\n)\r\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Error rate(4xx/ 5xx)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(cardiotrack_api_http_requests_total{status=\"4xx\"}[1m]))",
     "legendFormat": "4xx Client Errors"
    },
    {
     "expr": "sum(rate(cardiotrack_api_http_requests_total{status=\"5xx\"}[1m]))",
     "legendFormat": "5xx Server Errors"
    }
   ]
  }
 ]
}